blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://github.com/msi89/mapbox-react-native/discussions/categories/q-a
      about: Looking for help with your app? Please use discussions or gitter or stack overflow
    - name: 🚀 Discussions and Proposals
      url: https://github.com/msi89/mapbox-react-native/discussions/categories/ideas
      about: Discuss the future of RNMapbox, submit feature requests
